using System.IO.Compression;
using System.Text;

namespace Generator.Icons;

/// <summary>
/// Builds optimized binary files containing icons and metadata
/// from the source text file (prepares assets for the Lucide.Avalonia build process.).
/// </summary>
public class BuildCommand
{
    /// <summary>
    /// Path to the source text file containing icon definitions.
    /// </summary>
    public required string InputPath { get; init; }

    /// <summary>
    /// Path to the Lucide.Avalonia project where generated files will be added.
    /// </summary>
    public required string OutputPath { get; init; }

    public void Execute()
    {
        Console.WriteLine("Starting build task...");

        if (!Directory.Exists(OutputPath))
        {
            throw new DirectoryNotFoundException($"The directory '{OutputPath}' does not exist.");
        }

        var icons = ParseIcons(InputPath);

        Directory.CreateDirectory(Path.Combine(OutputPath, "Resources"));

        WriteBinaryIcons(icons);
        WriteBinaryMetadata(icons);
        WriteIconEnumCsSource(icons);
    }

    private void WriteBinaryIcons(LucideIconInfo[] icons)
    {
        Console.WriteLine("Compressing and writing icons...");

        var targetPath = Path.Combine(OutputPath, "Resources", "icons.bin");

        using var fileStream = File.Create(targetPath);
        using var brotliStream = new BrotliStream(fileStream, CompressionLevel.SmallestSize);

        using var writer = new BinaryWriter(brotliStream);

        foreach (var icon in icons)
        {
            writer.Write(icon.Geometry);
        }

        Console.WriteLine($"The icon file was successfully written to {targetPath}.");
    }

    private void WriteBinaryMetadata(LucideIconInfo[] icons)
    {
        Console.WriteLine("Compressing and writing metadata...");

        var targetPath = Path.Combine(OutputPath, "Resources", "metadata.bin");

        using var fileStream = File.Create(targetPath);
        using var brotliStream = new BrotliStream(fileStream, CompressionLevel.SmallestSize);

        using var writer = new BinaryWriter(brotliStream);

        foreach (var icon in icons)
        {
            writer.Write(string.Join(',', icon.Contributors));
            writer.Write(string.Join(',', icon.Categories));
            writer.Write(string.Join(',', icon.Tags));
        }

        Console.WriteLine($"The metadata file was successfully written to {targetPath}.");
    }

    private void WriteIconEnumCsSource(LucideIconInfo[] icons)
    {
        Console.WriteLine("Writing LucideIconKind.g.cs source...");

        var targetPath = Path.Combine(OutputPath, "LucideIconKind.g.cs");

        using var stream = File.Create(targetPath);
        using var writer = new StreamWriter(stream);

        writer.WriteLine("// <auto-generated />");
        writer.WriteLine();
        writer.WriteLine("namespace Lucide.Avalonia;");
        writer.WriteLine();
        writer.WriteLine("public enum LucideIconKind");
        writer.WriteLine("{");

        foreach (var icon in icons)
        {
            writer.WriteLine($"    {KebabToPascalCase(icon.Name)},");
        }

        writer.WriteLine("}");

        Console.WriteLine("LucideIconKind.g.cs source was written successfully.");
    }

    private static LucideIconInfo[] ParseIcons(string path)
    {
        var lines = File.ReadAllLines(path);
        var icons = new List<LucideIconInfo>();

        static string RemovePrefix(string value, string prefix)
        {
            if (value.StartsWith(prefix) == false)
            {
                throw new InvalidOperationException();
            }

            return value[prefix.Length..].Trim();
        }

        for (var i = 0; i < lines.Length; i += 6)
        {
            var nameLine = lines[i];
            var geometryLine = lines[i + 1];
            var contributorsLine = lines[i + 2];
            var categoriesLine = lines[i + 3];
            var tagsLine = lines[i + 4];

            var name = RemovePrefix(nameLine, "name:");
            var geometry = RemovePrefix(geometryLine, "geometry:");
            var contributors = RemovePrefix(contributorsLine, "contributors:");
            var categories = RemovePrefix(categoriesLine, "categories:");
            var tags = RemovePrefix(tagsLine, "tags:");

            var icon = new LucideIconInfo
            {
                Name = name,
                Geometry = geometry,
                Contributors = contributors.Split(','),
                Categories = categories.Split(','),
                Tags = tags.Split(',')
            };

            icons.Add(icon);
        }

        return [.. icons];
    }

    private static string KebabToPascalCase(string input)
    {
        if (string.IsNullOrWhiteSpace(input))
        {
            return input;
        }

        var sb = new StringBuilder();
        var nextUpper = true;

        for (int i = 0; i < input.Length; i++)
        {
            var c = input[i];

            if (c == '-')
            {
                nextUpper = true;
            }
            else
            {
                sb.Append(nextUpper ? char.ToUpper(c) : char.ToLower(c));
                nextUpper = false;
            }
        }

        return sb.ToString();
    }
}