name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build
        run: |
          dotnet build -c Debug src/Lucide.Avalonia/Lucide.Avalonia.csproj
          dotnet build -c Release src/Lucide.Avalonia/Lucide.Avalonia.csproj