name: Build Gallery (Native)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Build
        run: dotnet publish src/Lucide.Avalonia.Gallery/Lucide.Avalonia.Gallery.csproj -c Release -r win-x64 -o bin/

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: gallery-native
          path: | 
            bin/*exe
            bin/*dll
