name: Build & Publish

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

env:
  VERSION: ${{ github.ref_name }}

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build
        run: dotnet build -c Release src/Lucide.Avalonia/Lucide.Avalonia.csproj -p:Version=${{ env.VERSION }}

      - name: Pack
        run: dotnet pack -c Release -o . src/Lucide.Avalonia/Lucide.Avalonia.csproj -p:Version=${{ env.VERSION }}

      - name: Publish
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release create ${{ env.VERSION }}
          --repo ${{ github.event.repository.full_name }}
          --title ${{ env.VERSION }}
          --generate-notes
          --verify-tag

      - name: Build Native Gallery
        run: |
          dotnet publish src/Lucide.Avalonia.Gallery/Lucide.Avalonia.Gallery.csproj -c Release -r win-x64 -o bin/
          7z a lucide-gallery.7z bin\*.exe bin\*.dll

      - name: Upload Native Gallary
        run: gh release upload ${{ env.VERSION }} lucide-gallery.7z#'Gallary (Native)'
