name: Release Gallery (NativeAOT)

on:
  workflow_dispatch: 
    inputs:
      release_tag_name: 
        required: true

jobs:
  build-and-upload:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release_tag_name }}
          submodules: recursive

      - name: Build
        run: |
          dotnet publish src/Lucide.Avalonia.Gallery/Lucide.Avalonia.Gallery.csproj -c Release -r win-x64 -o bin/
          cd bin
          7z a ../icons-gallery-win-x64-aot.zip bin/*.exe bin/*.dll

      - name: Upload Gallery to Release
        run: gh release upload ${{ inputs.release_tag_name }} icons-gallery-win-x64-aot.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
