name: Release Gallery (NativeAOT)

on:
  workflow_dispatch: 
    inputs:
      release_tag_name: 
        required: true

jobs:
  build-and-upload:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release_tag_name }}

      - name: Build
        run: |
          dotnet publish src/Lucide.Avalonia.Gallery/Lucide.Avalonia.Gallery.csproj -c Release -r win-x64 -o bin/
          7z a icons-gallery.zip bin\*.exe bin\*.dll

      - name: Upload Gallery to Release
        run: gh release upload ${{ inputs.release_tag_name }} icons-gallery.zip#'Icons-Gallery (NativeAOT)'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
