name: Release Gallery (NativeAOT)

on:
  workflow_dispatch: 
    inputs:
      release_name: 
        required: true

jobs:
  build-and-upload:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          dotnet publish $gallery_project_path -c Release -r win-x64 -o bin/
          7z a icons-gallery.7z bin\*.exe bin\*.dll

      - name: Upload Gallery to Release
        run: gh release upload ${{ inputs.release_name }} icons-gallery.7z#'Icons-Gallery (NativeAOT)'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
