name: Update Icon Collection (Bot)

on:
  schedule:
    - cron: '0 2 * * 1'
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: 9.0.x

    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout lucide-icons
      run: git clone https://github.com/lucide-icons/lucide.git

    - name: Run Generator
      run: |
        dotnet restore ./src/LucideIcons.Generator
        dotnet run --project ./src/LucideIcons.Generator ./lucide ./src/Lucide.Avalonia/

    - name: Check Generated Code
      run: dotnet build ./src/Lucide.Avalonia/

    - name: Push Changes (if any)
      run: bash ./.github/scripts/update-icons.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}