name: Update Icon Collection (Bot)

on:
  schedule:
    - cron: '0 12 * * *'
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: 9.0.x

    - name: Setup Nushell
      run: |
        curl -fsSL https://apt.fury.io/nushell/gpg.key | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/fury-nushell.gpg
        echo "deb https://apt.fury.io/nushell/ /" | sudo tee /etc/apt/sources.list.d/fury.list
        sudo apt update
        sudo apt install nushell

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Checkout lucide-icons
      run: git clone https://github.com/lucide-icons/lucide.git

    - name: Run Generator
      run: |
        dotnet restore ./src/LucideIcons.Generator
        dotnet run --project ./src/LucideIcons.Generator ./lucide ./src/Lucide.Avalonia/

    - name: Check Generated Code
      run: dotnet build ./src/Lucide.Avalonia/

    - name: Push Changes (if any)
      run: bash .github/update-icons.sh
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}